- hosts: all
  vars:
    puertos:
      - 22
      - 80
      - 4440
      - 8080
      - 440
      - 7070
  tasks:
    - name: "Ver puertos"
      ansible.builtin.debug:
        msg: "La salida es {{ item | int }}"
      with_items: "{{ puertos }}"

    - name: "Chequear puertos"
      ansible.builtin.wait_for:
        host: 192.168.1.125
        #host2: 192.168.1.125
        port: "{{ item | int }}" 
        timeout: 10
        state: started
      register: salida
      with_items: "{{ puertos }}"
      ignore_errors: true

    - name: "Ver resultados"
      ansible.builtin.debug:
        msg: "La salida es {{ item }}"
      with_items: "{{ salida.results }}"
